# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


window.markers = []
window.divs = []
window.map = L.map('mapid').setView([
  49.7
  15.5
], 8)


$('document').on 'turbolinks:load', ->
  $('.selectize').selectize({
        create: true,
    sortField: 'text'
    })
  return


L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFydHljYXNoZXciLCJhIjoiY2p3bzBwa2NiMmQyczQ5bzIwenFrbWNmYiJ9.8vHaT7NMz3mszqg9uqu9hw',
  maxZoom: 18
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' + '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' + 'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>'
  id: 'mapbox.streets').addTo map

$ ->
  $('div.rowitem' ).each ->
     markers[$(this).attr("index")] = L.marker([
       $(this).attr("latitude")
       $(this).attr("longitude")
    ]).addTo(map).bindPopup("<b>" + $(this).attr("name") + "</b><br>"+$(this).attr("address")+ "<br>" +$(this).attr("city"))
    divs.push $(this)

$ ->
  $('div.rowitem').click ->
    map.setView([
      $(this).attr("latitude")
      $(this).attr("longitude")
      ], 15)
    window.markers[parseInt($(this).attr("index"))].openPopup()

window.search_stores = (text) ->
  if(!!text)
    text = text.toLowerCase()
    $('div.rowitem' ).each ->
      $(this).addClass "hidden"
      map.removeLayer markers[$(this).attr("index")]
      str = $(this).attr("name") + " - " + $(this).attr("address") + " - " +  $(this).attr("city") + " - " +  $(this).attr("postcode")
      str = str.toLowerCase()
      if text.includes str
        $(this).removeClass "hidden"
        map.addLayer markers[$(this).attr("index")]
  else
    $('.hidden').each ->
      $(this).removeClass "hidden"
      map.addLayer markers[$(this).attr("index")]
###
$ ->
  $('i.material-icons').click ->
      text = $('#search').val()
      search_stores text
###
$('#search').on 'keyup', (e) ->
  text = $('#search').val()
  if e.keyCode == 13
    search_stores text
  else if !(!!text)
    search_stores text
  return

popup = L.popup()
L.Map.invalidateSize();


# ---
# generated by js2coffee 2.2.0
