# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


window.markers = []
window.map = L.map('mapid').setView([
  49.7
  15.5
], 8)


# https://account.mapbox.com/access-tokens/ request access token
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFydHljYXNoZXciLCJhIjoiY2p3bzBwa2NiMmQyczQ5bzIwenFrbWNmYiJ9.8vHaT7NMz3mszqg9uqu9hw',
  maxZoom: 18
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' + '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' + 'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>'
  id: 'mapbox.streets').addTo map

$ ->
  $('div.rowitem' ).each ->
     markers.push L.marker([
       $(this).attr("latitude")
       $(this).attr("longitude")
    ]).addTo(map).bindPopup($(this).text())
      

$ ->
  $('div.rowitem').click ->
    map.setView([
      $(this).attr("latitude")
      $(this).attr("longitude")
      ], 15)
    window.markers[parseInt($(this).attr("id"))].openPopup()

popup = L.popup()
L.Map.invalidateSize();
# ---
# generated by js2coffee 2.2.0
